name: Build APK from Web

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install Cordova
      run: npm install -g cordova

    - name: Create Cordova project and inject web app
      run: |
        cordova create app com.dankert.clicker DanKertClicker
        cd app

        # заменить дефолтный web
        rm -rf www
        cp -r ../www www

        # копируем конфиг
        cp ../config.xml config.xml

        cordova platform add android
        cordova build android

    - name: Debug - list build files
      run: |
        echo "Searching APK files..."
        find . -type f -name "*.apk"

    - name: Upload APK (auto-detect path)
      uses: actions/upload-artifact@v4
      with:
        name: apk-build
        path: "**/*.apk"
